export const teamMembers = [
    {
        name: "Lutz Lungwitz",
        roleEN: "1st Chairman",
        roleDE: "1. Vorsitzender",
        teamEN: "Board DMWV",
        teamDE: "Vorstand DMWV",
        image: "/images/LutzLungwitz.jpeg",
    },
    {
        name: "Axel Donald Sauer",
        roleEN: "1st Deputy Chairman",
        roleDE: "1. stellv. Vorsitzender",
        teamEN: "Board DMWV",
        teamDE: "Vorstand DMWV",
        image: "/images/AxelDonaldSauer.jpeg",
    },
    {
        name: "Prof. Dr. Joachim Willms",
        roleEN: "2nd Deputy Chairman",
        roleDE: "2. stellv. Vorsitzender",
        teamEN: "Board DMWV",
        teamDE: "Vorstand DMWV",
        image: "/images/ProfDrJoachimWillms.jpeg",
    },
    {
        name: "Karsten Urspruch",
        roleEN: "Board Member",
        roleDE: "Vorstandsmitglied",
        teamEN: "Board DMWV",
        teamDE: "Vorstand DMWV",
        image: "/images/KarstenUrspruch.jpeg",
    },
    {
        name: "Rigobert Walzer",
        roleEN: "Treasurer",
        roleDE: "Schatzmeister",
        teamEN: "Board DMWV",
        teamDE: "Vorstand DMWV",
        image: "/images/RigobertWalzer.jpeg",
    },
    {
        name: "Michael Häckel",
        roleEN: "Board Member (associated)",
        roleDE: "Vorstandsmitglied (assoziiert)",
        teamEN: "Board DMWV",
        teamDE: "Vorstand DMWV",
        image: "/images/MichaelHäckel.jpeg",
    },

    //  team Projektentwicklung, Bauen und Technik
    {
        name: "Martin Hofmann",
        roleEN: "Dipl.- Ing, Architect",
        roleDE: "Dipl.- Ing, Architekt",
        teamEN: "Project Development, Construction and Technology",
        teamDE: "Projektentwicklung, Bauen und Technik",
        image: "/placeholder.svg?height=600&width=400",
    },
    {
        name: "Dipl.-Ing. Architekt Joachim Langenbach",
        roleEN: "Member",
        roleDE: "Mitglied",
        teamEN: "Project Development, Construction and Technology",
        teamDE: "Projektentwicklung, Bauen und Technik",
        image: "/placeholder.svg?height=600&width=400",
    },

    // Qualitätsmanagement
    {
        name: "Regina Nolte",
        roleEN: "Principal of VPT Academy, Massage/Physiotherapy School",
        roleDE: "Schulleiterin der VPT Akademie, Massage-/Physiotherapeuten-Schule",
        teamEN: "Quality Management",
        teamDE: "Qualitätsmanagement",
        image: "/placeholder.svg?height=600&width=400",
    },
    {
        name: "Olaf Seiche",
        roleEN: "Head of Tourism Division TÜV Rheinland Group",
        roleDE: "Bereichsleiter Tourismus TÜV Rheinland Group",
        teamEN: "Quality Management",
        teamDE: "Qualitätsmanagement",
        image: "/placeholder.svg?height=600&width=400",
    },
    {
        name: "Prof. Dr. med. Dr. phil. Winfried Banzer",
        roleEN: "Head of Sports Medicine Department at Johann Wolfgang Goethe University Frankfurt",
        roleDE: "Leiter der Abteilung Sportmedizin der Johann Wolfgang Goethe-Universität Frankfurt",
        teamEN: "Medicine and Lifestyle",
        teamDE: "Medizin und Lebensführung",
        image: "/placeholder.svg?height=600&width=400",
    },
    {
        name: "Prof. Dr. Tobias Esch",
        roleEN: "Professor at Coburg University, Integrierte Gesundheitsförderung Study Program",
        roleDE: "Professor an der Hochschule Coburg, Studiengang der Integrierenden Gesundheitsförderung",
        teamEN: "Medicine and Lifestyle",
        teamDE: "Medizin und Lebensführung",
        image: "/placeholder.svg?height=600&width=400",
    },
    {
        name: "Prof. Dr. Kai Illing",
        roleEN: "Faculty of Health Management in Tourism, Fachhochschule Graz/Bad Gleichenberg",
        roleDE: "Fakultät für Gesundheitsmanagement im Tourismus, Fachhochschule Graz/Bad Gleichenberg",
        teamEN: "Medicine and Lifestyle",
        teamDE: "Medizin und Lebensführung",
        image: "/placeholder.svg?height=600&width=400",
    },
    {
        name: "Dr. Arnulf Preusler",
        roleEN: "Internist, General Practitioner",
        roleDE: "Internist, Allgemeinmediziner",
        teamEN: "Medicine and Lifestyle",
        teamDE: "Medizin und Lebensführung",
        image: "/placeholder.svg?height=600&width=400",
    },
    {
        name: "Dr. Peter Puhala",
        roleEN: "Neurologist and Psychiatrist/Psychotherapist",
        roleDE: "Facharzt für Neurologie u. Psychiatrie/Psychotherapie",
        teamEN: "Medicine and Lifestyle",
        teamDE: "Medizin und Lebensführung",
        image: "/placeholder.svg?height=600&width=400",
    },
    {
        name: "Matthias Rolle",
        roleEN: "Medical Doctor, Medical Director and Managing Director of Gesundheitszentrum Océano, Teneriffa",
        roleDE: "Mediziner, Ärztlicher Leiter und Geschäftsführer Gesundheitszentrum Océano, Teneriffa",
        teamEN: "Medicine and Lifestyle",
        teamDE: "Medizin und Lebensführung",
        image: "/placeholder.svg?height=600&width=400",
    },
    {
        name: "Prof. Dr. Dr. Eberhard Volger",
        roleEN: "Chairman of the Scientific Advisory Board of the European Center for Natural Medicine, Sebastian Kneipp Institute GmbH",
        roleDE: "Vorsitzender des wissenschaftlichen Beirats des Europäischen Gesundheitszentrums für Naturheilverfahren, Sebastian Kneipp Institut GmbH",
        teamEN: "Medicine and Lifestyle",
        teamDE: "Medizin und Lebensführung",
        image: "/placeholder.svg?height=600&width=400",
    },
    {
        name: "Dr. Bernd-Rainer Voß",
        roleEN: "Gynecologist",
        roleDE: "Gynäkologe",
        teamEN: "Medicine and Lifestyle",
        teamDE: "Medizin und Lebensführung",
        image: "/placeholder.svg?height=600&width=400",
    },
    {
        name: "Dr. Jürgen Wahlmann",
        roleEN: "Dentist, Dr. Wahlmann, Dr. Grieße and Partner — Aesthetic Dentistry",
        roleDE: "Zahnarzt, Dr. Wahlmann, Dr. Grieße und Partner — ästhetische Zahnheilkunde",
        teamEN: "Medicine and Lifestyle",
        teamDE: "Medizin und Lebensführung",
        image: "/placeholder.svg?height=600&width=400",
    },
    // Personal und Ausbildung
    {
        name: "Jens Engelke",
        roleEN: "Managing Director of Baltic College GmbH, University of Applied Sciences, Güstrow",
        roleDE: "Geschäftsführer des Baltic College GmbH, University of Applied Sciences, Güstrow",
        teamEN: "Personnel and Education",
        teamDE: "Personal und Ausbildung",
        image: "/placeholder.svg?height=600&width=400",
    },
    {
        name: "Detlef Jarosch",
        roleEN: "Dipl.-Geogr. and Dipl.-Kfm., Owner of hrc jarosch Consulting",
        roleDE: "Dipl.-Geogr. und Dipl.-Kfm., Inhaber der hrc jarosch Unternehmensberatung",
        teamEN: "Personnel and Education",
        teamDE: "Personal und Ausbildung",
        image: "/placeholder.svg?height=600&width=400",
    },
    {
        name: "Regina Nolte",
        roleEN: "Principal of VPT Academy, Massage/Physiotherapy School",
        roleDE: "Schulleiterin der VPT Akademie, Massage-/Physiotherapeuten-Schule",
        teamEN: "Personnel and Education",
        teamDE: "Personal und Ausbildung",
        image: "/placeholder.svg?height=600&width=400",
    },
];